import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
// -> One way to import CSS file (available globally in all components)
// import '../styles/globals.css'
// -> Another way to import CSS file (available in particular component only). Then use it as {styles.cont}
// import styles from '../styles/globals.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 27px;
          }
        `}
      </style>
      {/* Head tag of nextjs/head to inject code into head tag of HTML page */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, huntingcoder, blog, coding"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* To run or inject custom javascript in the application [May cause delay in pageload; bad user experience; prefer nextjs/script feature] */}
      {/* <script src='my_script.js'></script> */}
      {/* <Script src="/my_script.js" strategy="lazyOnload"></Script> */}
      {/* To run or inject custom javascript in the application [Inbuilt next js feature to specify when to run the script- "beforeInteractive", "afterInteractive", or "lazyOnload"] */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <div className={styles.imgWrap}>
          <Image src="/home.jpg" className={styles.myImg} width={436} height={290}/>
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder!
        </p>
        
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

    </div>
  )
}
