import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      {/* Head tag of nextjs/head to inject code into head tag of HTML page */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, huntingcoder, blog, coding"/>
        <link rel="icon" href="/favicon.ico" />
        {/* To run or inject custom javascript in the application [May cause delay in pageload; bad user experience; prefer nextjs/script feature] */}
        {/* <script src='my_script.js'></script> */}
      </Head>
      
      {/* To run or inject custom javascript in the application [Inbuilt next js feature to specify when to run the script- "beforeInteractive", "afterInteractive", or "lazyOnload"] */}
      {/* <Script src="/my_script.js" strategy="lazyOnload"></Script> */}

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder!
        </p>
        
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScritp is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

    </div>
  )
}
